Show lambda term and word types in frontend
UUDigitalHumanitieslab/parseport pull request #14
Opened 2023-11-29 15:26 UTC by bbonf

Closes #9  

Some notes:
- The fact that on the frontend `parse()` uses `export()` seems quite backwards, but it made it very easy to add a new response type.
- It isn't ideal that everything is parsed from scratch on every export type (while the spindle-server already provides everything in one call), but in practice it doesn't matter much.

2023-12-01 12:11 UTC, XanderVertegaal requested changes
Nice, well done! 👍 And thanks for laying out the groundwork for the proof export. That should be a breeze now :) I agree that it's fine for the analysis to run twice when you parse  + export. I don't think we should be worried about having too much traffic.

I have left some frontend comments. The caption for 'Term' and a table header are the most important; you may choose to implement/ignore the others as you see fit.

In addition, I noticed that parse results and export buttons remain visible after the parser returns an error. Maybe we could hide them instead (perhaps even already when the user changes the input). Feel free to make a separate issue out of this if you don't want to include that here, though.

2023-12-06 15:32 UTC, bbonf commented on frontend/src/app/spindle/spindle.component.html
> +        <tr *ngFor="let phrase of lexicalPhrases; index as i">
I'm happy to do that, but I'm not sure what the correct titles would be

2023-12-06 15:33 UTC, bbonf commented on frontend/src/app/spindle/spindle.component.html
> +                {{ i }}
The reason for using zero-based indexing is that these match the constants in the term (c0, c1, ...)

2023-12-06 15:35 UTC, bbonf commented on frontend/src/app/spindle/spindle.component.ts
> +                    this.parsed = true;
This is indeed redundant

2024-01-18 17:20 UTC, XanderVertegaal approved these changes

2024-01-19 15:14 UTC, merged